# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89f1ba66b9367c359c31f3861e00e6add4ea5eee0f83a7578dc6110868a399656eedfb33e47492a1ed555299ddbb836b6641f19f68ce4cfe2feb5efd2c2d7b33

test:
  secret_key_base: 14e895854aab118fe36df9a7ea42e351aadbe6c1d6441a443f3a14a4a7c19a16a01ab459f3b8ed51a6daba6320a1b075d5fb2a0a313c370a07a6ded2c80cf51a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
